# Generated by Django 3.2.3 on 2021-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
